### ISSUE TITLE
Rubocop - Hard to commit changes with issues.

### ISSUE THREAD

**Issue by bkuhlmann** [hanami/cli#19]
## Overview

When committing to this project (in my case, a fork), I'm not able to push new commits to the remote repo due to Rubocop failing. This happens because I *always* run Rubocop as a [Git Hook](https://github.com/bkuhlmann/dotfiles/blob/master/home_files/.config/git/hooks/pre-push.tt#L40) in order to resolve issues before finding out via a failed CI build.

If you are serious about using Rubocop in this project (kudos for including it), it'd be a good idea to add it to the CI build process to ensure it is being used properly by this project. I might suggest this [configuration](https://github.com/bkuhlmann/code_quality/blob/master/configurations/rubocop/ruby.yml) as a good configuration to use. :)

## Steps to Recreate

Regardless of whether you auto-run Rubocop as a Git Hook or not, you can see the issues by running:

`bundle exec rubocop`

## Screenshots/Screencasts

![shell](https://user-images.githubusercontent.com/50245/31585674-37942636-b183-11e7-8670-f03d6bffd5ae.png)

## Workaround

Delete this line:

`gem 'rubocop', '0.49.1', require: false`

...from the project `Gemfile`. That allows my Git Hook to see that Rubocop isn't configured for the project and I can commit code successfully.

**Comment by cllns** [comment]
Thanks for opening this. This issue is actually fixed (for me, at least) on the `develop` branch, where new feature development happens (and will be merged into master when release). Going to close this issue since this should be fixed on `master` soon, but...

We need to add better contribution instructions. In Semantic Versioning terms: the `develop` will be the next minor version. `master` is work for the next patch version release. Those are our rules for the other `hanami` repos, and I think they apply here too, even though it's pre-1.0.

Also, just so you know: we're slowly adopting Rubocop for Hanami repos. [You can see this in the Rubocop config for `hanami-utils`](https://github.com/hanami/utils/blob/master/.rubocop.yml) , where we use a URL to inherit from [the config for the main (`hanami/hanami`) repo](https://github.com/hanami/hanami/blob/master/.rubocop.yml). It's quite minimal for now.
