### ISSUE TITLE
cli does not works when using hanami 2.0-alpha releases

### ISSUE THREAD

**Issue by morissetcl** [hanami/cli#2]
Hi,

I am trying to run an Hanami app with 2.0-alpha releases and I am not able to run any command.
For each command I tried I had the following result:
```
➜  cockpit git:(master) ✗ bundle exec hanami server                                                                                                                      [2.7.3]
Commands:
  hanami version
```

My gemfile

```
source 'https://rubygems.org'

gem 'rake'
gem 'hanami-model'
%w[hanami hanami-cli hanami-controller hanami-router hanami-utils hanami-view].each do |name|
  gem name, "~> 2.0.alpha"
end

gem 'sqlite3'
...
```

I use ruby `2.7.3`
For your information when I downgrade to `1.3.4` everything works.

Do you have any idea why it does not work as expected ?

Many thanks.

**Comment by cllns** [comment]
The alpha is incomplete right now and doesn't include `bundle exec hanami server` yet.

I recommend using `bundle exec rackup` to get a server running in a Hanami 2 app.

More than that though, the upgrade from 1.3 to 2.0 will be substantial, and involve much more than updating the Gemfile. We're working on that documentation now, but it's not available yet. I wouldn't really recommend upgrading from 1.3 to 2.0 yet for this alpha, since it is a lot of work and things will change.

If you want to try out Hanami 2 with a new application, you can use the application template: https://github.com/hanami/hanami-2-application-template. This won't be how we distribute it for the full release, but it's how we're doing it for the alpha.

We'll definitely implement a `hanami server` command before the official 2.0 release.

Closing but feel free to re-open or add comments if you have more questions.
