### ISSUE TITLE
`hanami generate action` does not generate views and templates

### ISSUE THREAD

**Issue by vikdotdev** [hanami/cli#48]
By the look of #33 it seems that the generation of views and templates was dropped for reasons unclear. I couldn't find any open tasks/issues for it.

If the intention is to add them back at some point I would be glad to give it a shot.

**Comment by cllns** [comment]
Hi @vikdotdev, thanks for your interest. We've decided to ship Hanami 2.0 without the view (or model) layers in order to get it shipped faster. Once that's released, we'll work to add the view (and model) layer support back in and release them in Hanami 2.1.

I suspect there will be a way to make `hanami-view` work with 2.0 by adding some files, it just won't be supported or integrated as well as the rest of the framework until 2.1.
