### ISSUE TITLE
Is `SPEC_ROOT` configured in `spec_helper.rb` used?

### ISSUE THREAD

**Issue by janko** [hanami/cli#60]
I noticed these two lines at the top of the `spec_helper.rb` generated by `hanami new`:

```rb
require "pathname"
SPEC_ROOT = Pathname(__dir__).realpath.freeze
```

Are these used by Hanami? It's just something that I haven't seen in other RSpec setups, and was wondering if it can be skipped for new Hanami apps, to keep the code minimalistic.

**Comment by janko** [comment]
This is probably too nitpicky. I will close the issue, and open more important ones in the future 😛

**Comment by timriley** [comment]
Yeah, these aren't strictly necessary.

Personally, I find myself defining these in nearly all of my spec helpers because it's useful for when you e.g. want to reference paths to files within the spec/ directory.

Here's one example:

```ruby
VCR.configure do |config|
  config.cassette_library_dir = SPEC_ROOT.join("../tmp/vcr_casettes")
```

And another:

```ruby
Capybara.save_path = SPEC_ROOT.join("../tmp/capybara-screenshot").expand_path.to_s
```

Both of these examples actually reference things _outside_ the spec root, but we can't exactly rely on `Hanami.app.root` at this point because this kind of test setup code is being executed before the Hanami app even boots.

Another place I've used it is when I want to refer to file fixtures or other such things that are located inside my `spec/` dir.

I'm not opposed to getting rid of it, however. I wonder what @jodosha or @solnic think.

**Comment by solnic** [comment]
I think it's very convenient to have that constant.
